import { buildMapStyle, UEC_MAP_SOURCE_ID } from "@e-chan1007/uec-map-sdk";
import type { FilterSpecification, LayerSpecification } from "maplibre-gl";

export const useMapStyle = (
  floor: Ref<number>,
  shouldUseExtrusion: Ref<boolean>,
  language: Ref<string>,
) =>
  computed(() => {
    const withLanguageSuffix = (base: string) =>
      language.value === "en" ? `${base}:en` : base;

    const areaLayers: LayerSpecification[] = [
      {
        id: "areas_outline",
        type: "line",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "areas",
        minzoom: 0,
        paint: {
          "line-color": "#cccccc",
          "line-width": 4,
        },
      },
      {
        id: "areas",
        type: "fill",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "areas",
        minzoom: 0,
        paint: {
          "fill-color": "#fafafa",
        },
      },
    ];

    const areaLabelLayers: LayerSpecification[] = [
      {
        id: "areas_label",
        type: "symbol",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "areas_label",
        minzoom: 0,
        maxzoom: 17,
        layout: {
          "text-field": ["get", withLanguageSuffix("name")],
          "text-size": 16,
          "text-max-width": 12,
        },
        paint: {
          "text-color": "#000000",
          "text-halo-color": "#FFFFFF",
          "text-halo-width": 2,
        },
      },
    ];

    const pathLayers: LayerSpecification[] = [
      {
        id: "paths_outline",
        type: "line",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "paths",
        filter: ["!=", "hidden", true],
        minzoom: 0,
        paint: {
          "line-color": "#666666",
          "line-width": [
            "interpolate",
            ["exponential", 2],
            ["zoom"],
            10,
            ["+", ["*", ["get", "weight"], ["^", 2, -6]], 2],
            24,
            ["+", ["*", ["get", "weight"], ["^", 2, 8]], 2],
          ],
        },
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
      },
      {
        id: "paths_inner",
        type: "line",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "paths",
        filter: ["!=", "hidden", true],
        minzoom: 0,
        paint: {
          "line-color": "#FFFFFF",
          "line-width": [
            "interpolate",
            ["exponential", 2],
            ["zoom"],
            10,
            ["*", ["get", "weight"], ["^", 2, -6]],
            24,
            ["*", ["get", "weight"], ["^", 2, 8]],
          ],
        },
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
      },
    ];

    const gateIconLayers: LayerSpecification[] = [
      {
        id: "gates-icon-shadow",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "gates",
        minzoom: 17,
        paint: {
          "circle-radius": 18,
          "circle-blur": 0.7,
          "circle-color": "#000000AA",
          "circle-translate": [0, 2],
        },
      },
      {
        id: "gates-icon-background",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "gates",
        minzoom: 17,
        paint: {
          "circle-radius": 14,
          "circle-color": "#969696",
          "circle-stroke-color": "#FFFFFF",
          "circle-stroke-width": 2,
        },
      },
      {
        id: "gates-label",
        type: "symbol",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "gates",
        minzoom: 17,
        layout: {
          "icon-image": MAP_ICONS["material-symbols:gate"],
          "icon-size": 0.8,
          "icon-padding": 0,
          "text-padding": 0,
          "text-allow-overlap": false,
          "icon-allow-overlap": true,
          "text-field": ["get", withLanguageSuffix("name")],
          "text-optional": true,
          "text-size": 12,
          "text-max-width": 16,
          "text-offset": [0, 1.5],
        },
        paint: {
          "text-color": "#000000",
          "icon-color": "#FFFFFF",
          "text-halo-color": "#FFFFFF",
          "text-halo-width": 2,
        },
      },
    ];

    const buildingLayers: LayerSpecification[] = [
      {
        id: "buildings",
        type: "fill",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings",
        minzoom: 0,
        paint: {
          "fill-color": [
            "match",
            ["get", "area"],
            "east",
            "#4eb562",
            "west",
            "#f66950",
            "100th",
            "#43acdd",
            "#969696",
          ],
          "fill-opacity": [
            "step",
            ["zoom"],
            ["match", ["get", "type"], "utility", 0.5, 1],
            20,
            0.15,
          ],
        },
      },
    ];

    const buildingIconLayers: LayerSpecification[] = [
      {
        id: "buildings-icon-shadow",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        filter: ["!=", ["get", "type"], "utility"],
        minzoom: 17,
        maxzoom: 20,
        paint: {
          "circle-radius": 18,
          "circle-blur": 0.7,
          "circle-color": "#000000AA",
          "circle-translate": [0, 2],
        },
      },
      {
        id: "buildings-icon-background",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        filter: ["!=", ["get", "type"], "utility"],
        minzoom: 17,
        maxzoom: 20,
        paint: {
          "circle-radius": 16,
          "circle-color": [
            "match",
            ["get", "type"],
            "academic",
            "#1895d4",
            "office",
            "#29b90c",
            "community",
            "#ffbb00",
            "residential",
            "#9126c7",
            "#969696",
          ],
          "circle-stroke-color": "#FFFFFF",
          "circle-stroke-width": 2,
        },
      },
      {
        id: "buildings-label",
        type: "symbol",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        filter: ["!=", ["get", "type"], "utility"],
        minzoom: 17,
        maxzoom: 20,
        layout: {
          "icon-image": [
            "match",
            ["get", "type"],
            "academic",
            MAP_ICONS["mdi:town-hall"],
            "office",
            MAP_ICONS["material-symbols:domain"],
            "community",
            MAP_ICONS["material-symbols:groups"],
            "residential",
            MAP_ICONS["material-symbols:home"],
            "fountain",
            MAP_ICONS["mdi:fountain"],
            MAP_ICONS["material-symbols:square"],
          ],
          "icon-padding": 0,
          "text-padding": 0,
          "text-allow-overlap": false,
          "icon-allow-overlap": true,
          "text-field": ["get", withLanguageSuffix("name")],
          "text-optional": true,
          "text-size": 14,
          "text-max-width": 16,
          "text-offset": [0, 1.5],
        },
        paint: {
          "text-color": "#000000",
          "icon-color": "#FFFFFF",
          "text-halo-color": "#FFFFFF",
          "text-halo-width": 2,
        },
      },
      {
        id: "buildings-alt-label",
        type: "symbol",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        filter: ["!=", ["get", "type"], "utility"],
        minzoom: 17,
        maxzoom: 20,
        layout: {
          "text-padding": 0,
          "text-field": ["get", withLanguageSuffix("altname")],
          "text-size": 10,
          "text-anchor": "top",
          "text-optional": true,
          "text-offset": [0, 3],
        },
        paint: {
          "text-color": "#000000",
          "text-halo-color": "#FFFFFF",
          "text-halo-width": 1,
        },
      },
    ];

    const buildingDetailIconLayers: LayerSpecification[] = [
      {
        id: "buildings-detail-icon-shadow",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        filter: ["==", ["get", "type"], "utility"],
        minzoom: 19,
        maxzoom: 20,
        paint: {
          "circle-radius": 16,
          "circle-blur": 0.7,
          "circle-color": "#000000AA",
          "circle-translate": [0, 2],
        },
      },
      {
        id: "buildings-detail-icon-background",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        filter: ["==", ["get", "type"], "utility"],
        minzoom: 19,
        maxzoom: 20,
        paint: {
          "circle-radius": 14,
          "circle-color": "#969696",
          "circle-stroke-color": "#FFFFFF",
          "circle-stroke-width": 2,
        },
      },
      {
        id: "buildings-detail-label",
        type: "symbol",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        filter: ["==", ["get", "type"], "utility"],
        minzoom: 19,
        maxzoom: 20,
        layout: {
          "icon-image": MAP_ICONS["material-symbols:room-preferences"],
          "icon-size": 0.8,
          "icon-padding": 0,
          "text-padding": 0,
          "text-allow-overlap": false,
          "icon-allow-overlap": true,
          "text-field": ["get", withLanguageSuffix("name")],
          "text-optional": true,
          "text-size": 10,
          "text-max-width": 16,
          "text-offset": [0, 1.5],
        },
        paint: {
          "text-color": "#000000",
          "icon-color": "#FFFFFF",
          "text-halo-color": "#FFFFFF",
          "text-halo-width": 1,
        },
      },
      {
        id: "buildings-detail-alt-label",
        type: "symbol",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        filter: ["==", ["get", "type"], "utility"],
        minzoom: 19,
        maxzoom: 20,
        layout: {
          "text-padding": 0,
          "text-field": ["get", withLanguageSuffix("altname")],
          "text-optional": true,
          "text-size": 10,
          "text-anchor": "top",
          "text-offset": [0, 2],
        },
        paint: {
          "text-color": "#000000",
          "text-halo-color": "#FFFFFF",
          "text-halo-width": 1,
        },
      },
    ];

    const extrusionLayers: LayerSpecification[] = [
      {
        id: "building-extrusion",
        type: "fill-extrusion",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors",
        minzoom: 0,
        layout: {
          visibility: shouldUseExtrusion.value ? "visible" : "none",
        },
        filter: ["<", ["zoom"], 20],
        paint: {
          "fill-extrusion-color": "#AAAAAA",
          "fill-extrusion-base": ["*", ["-", ["get", "floor"], 1], 5],
          "fill-extrusion-opacity": 1,
          "fill-extrusion-vertical-gradient": false,
          "fill-extrusion-height": ["*", ["get", "floor"], 5],
        },
      },
      {
        id: "floor-extrusion",
        type: "fill-extrusion",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors",
        minzoom: 0,
        layout: {
          visibility: shouldUseExtrusion.value ? "visible" : "none",
        },
        filter: [
          "all",
          [">=", ["zoom"], 20],
          ["<=", ["get", "floor"], floor.value],
        ],
        paint: {
          "fill-extrusion-color": [
            "match",
            ["get", "type"],
            "misc",
            "#969696",
            "corridor",
            "#EAEAEA",
            "elevator",
            "#C8C8C8",
            "stairs",
            "#C8C8C8",
            "lecture_room",
            "#D3F1FF",
            "wc_universal",
            "#AC8DCE",
            "wc_unknown",
            "#C7A3C6",
            "wc_men",
            "#8DA2DB",
            "wc_women",
            "#CE8D9B",
            "common_space",
            "#FFEBA6",
            "office",
            "#B1E4B2",
            "#31A6D4",
          ],
          "fill-extrusion-base": ["*", ["-", ["get", "floor"], 1], 5],
          "fill-extrusion-opacity": 1,
          "fill-extrusion-vertical-gradient": false,
          "fill-extrusion-height": [
            "+",
            ["*", ["-", ["get", "floor"], 1], 5],
            0.01,
          ],
        },
      },
      {
        id: "ceiling-extrusion",
        type: "fill-extrusion",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors",
        minzoom: 0,
        layout: {
          visibility: shouldUseExtrusion.value ? "visible" : "none",
        },
        filter: [
          "all",
          [">=", ["zoom"], 20],
          ["<", ["get", "floor"], floor.value],
        ],
        paint: {
          "fill-extrusion-color": "#AAAAAA",
          "fill-extrusion-base": ["*", ["get", "floor"], 5],
          "fill-extrusion-opacity": 1,
          "fill-extrusion-vertical-gradient": false,
          "fill-extrusion-height": ["*", ["get", "floor"], 5],
        },
      },
      {
        id: "floor-wall-extrusion",
        type: "fill-extrusion",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floor_walls",
        minzoom: 0,
        layout: {
          visibility: shouldUseExtrusion.value ? "visible" : "none",
        },
        filter: [
          "all",
          [">=", ["zoom"], 20],
          ["<=", ["get", "floor"], floor.value],
        ],
        paint: {
          "fill-extrusion-color": "#AAAAAA",
          "fill-extrusion-base": ["*", ["-", ["get", "floor"], 1], 5],
          "fill-extrusion-opacity": 1,
          "fill-extrusion-vertical-gradient": false,
          "fill-extrusion-height": [
            "-",
            ["*", ["get", "floor"], 5],
            ["case", ["==", ["get", "floor"], floor.value], 4, 0],
          ],
        },
      },
    ];

    const floorIconFilter: FilterSpecification = [
      "all",
      ["==", ["get", "floor"], floor.value],
      ["!", ["in", ["get", "type"], ["literal", ["corridor", "misc"]]]],
    ];

    const floorLayers: LayerSpecification[] = [
      {
        id: "floors",
        type: "fill",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors",
        minzoom: 20,
        filter: ["==", ["get", "floor"], floor.value],
        layout: {
          visibility: shouldUseExtrusion.value ? "none" : "visible",
        },
        paint: {
          "fill-color": [
            "match",
            ["get", "type"],
            "misc",
            "#969696",
            "corridor",
            "#EAEAEA",
            "elevator",
            "#C8C8C8",
            "stairs",
            "#C8C8C8",
            "lecture_room",
            "#D3F1FF",
            "wc_universal",
            "#AC8DCE",
            "wc_unknown",
            "#C7A3C6",
            "wc_men",
            "#8DA2DB",
            "wc_women",
            "#CE8D9B",
            "common_space",
            "#FFEBA6",
            "office",
            "#B1E4B2",
            "#31A6D4",
          ],
          "fill-outline-color": "#232323",
        },
      },
      {
        id: "floors-icon-shadow",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors_label",
        minzoom: 20,
        filter: floorIconFilter,
        layout: {
          visibility: shouldUseExtrusion.value ? "none" : "visible",
        },
        paint: {
          "circle-radius": 16,
          "circle-blur": 0.7,
          "circle-color": "#000000AA",
          "circle-translate": [0, 2],
        },
      },
      {
        id: "floors-icon-background",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors_label",
        minzoom: 20,
        filter: floorIconFilter,
        layout: {
          visibility: shouldUseExtrusion.value ? "none" : "visible",
        },
        paint: {
          "circle-radius": 14,
          "circle-color": [
            "match",
            ["get", "type"],
            "lecture_room",
            "#3abdf9",
            "wc_universal",
            "#8737dc",
            "wc_unknown",
            "#9527b1",
            "wc_men",
            "#234ec7",
            "wc_women",
            "#c72347",
            "common_space",
            "#f7c71c",
            "office",
            "#0ca70e",
            "#969696",
          ],
          "circle-stroke-color": "#FFFFFF",
          "circle-stroke-width": 2,
        },
      },
      {
        id: "floors-label",
        type: "symbol",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors_label",
        minzoom: 20,
        filter: floorIconFilter,
        layout: {
          visibility: shouldUseExtrusion.value ? "none" : "visible",
          "icon-image": [
            "match",
            ["get", "type"],
            "elevator",
            MAP_ICONS["material-symbols:elevator-outline"],
            "stairs",
            MAP_ICONS["material-symbols:stairs-2"],
            "lecture_room",
            MAP_ICONS["material-symbols:co-present"],
            "wc_universal",
            MAP_ICONS["map:toilet"],
            "wc_unknown",
            MAP_ICONS["map:toilet"],
            "wc_men",
            MAP_ICONS["material-symbols:man"],
            "wc_women",
            MAP_ICONS["material-symbols:woman"],
            "common_space",
            MAP_ICONS["material-symbols:groups"],
            "office",
            MAP_ICONS["material-symbols:checkbook"],
            MAP_ICONS["mdi:town-hall"],
          ],
          "icon-size": 0.8,
          "icon-padding": 0,
          "text-padding": 0,
          "text-field": ["get", withLanguageSuffix("name")],
          "text-size": 12,
          "text-max-width": 16,
          "text-offset": [0, 1.5],
          "icon-allow-overlap": true,
          "text-allow-overlap": true,
        },
        paint: {
          "text-color": "#000000",
          "icon-color": "#FFFFFF",
          "text-halo-color": "#FFFFFF",
          "text-halo-width": 1,
        },
      },
    ];

    const osmLayers: LayerSpecification[] = [
      {
        id: "water",
        type: "fill",
        source: "osm",
        "source-layer": "water",
        paint: {
          "fill-color": "#ddecfcff",
        },
      },
      {
        id: "buildings-2d",
        type: "fill",
        source: "osm",
        "source-layer": "building",
        minzoom: 13,
        paint: {
          "fill-color": "#f0f0f0",
          "fill-outline-color": "#eaeaea",
        },
      },
      {
        id: "roads-minor",
        type: "line",
        source: "osm",
        "source-layer": "transportation",
        minzoom: 12,
        filter: ["in", "class", "minor", "street", "service"],
        paint: {
          "line-color": "#f0f0f0",
          "line-width": 3,
        },
      },
      {
        id: "roads-major",
        type: "line",
        source: "osm",
        "source-layer": "transportation",
        filter: [
          "in",
          "class",
          "motorway",
          "trunk",
          "primary",
          "secondary",
          "tertiary",
        ],
        paint: {
          "line-color": "#eaeaea",
          "line-width": 3,
        },
      },
    ];

    return buildMapStyle({
      version: 8,
      sources: {
        osm: {
          type: "vector",
          url: "pmtiles://https://tile.openstreetmap.jp/static/planet.pmtiles",
          attribution: "&copy; OpenStreetMap contributors",
        },
      },
      layers: [
        ...osmLayers,
        ...areaLayers,
        ...pathLayers,
        ...buildingLayers,
        ...extrusionLayers,
        ...buildingDetailIconLayers,
        ...gateIconLayers,
        ...buildingIconLayers,
        ...floorLayers,
        ...areaLabelLayers,
      ],
    });
  });
