import { buildMapStyle, UEC_MAP_SOURCE_ID } from "@e-chan1007/uec-map-sdk";
import type { FilterSpecification, LayerSpecification } from "maplibre-gl";

export const useMapStyle = (
  floor: Ref<number>,
  shouldUseExtrusion: Ref<boolean>,
) =>
  computed(() => {
    const areaLayers: LayerSpecification[] = [
      {
        id: "areas_outline",
        type: "line",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "areas",
        minzoom: 0,
        maxzoom: 22,
        paint: {
          "line-color": "#cccccc",
          "line-width": 4,
        },
      },
      {
        id: "areas",
        type: "fill",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "areas",
        minzoom: 0,
        maxzoom: 22,
        paint: {
          "fill-color": "#fafafa",
        },
      },
    ];

    const pathLayers: LayerSpecification[] = [
      {
        id: "paths_outline",
        type: "line",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "paths",
        filter: [">=", ["get", "weight"], 2],
        minzoom: 0,
        maxzoom: 22,
        paint: {
          "line-color": "#666666",
          "line-width": [
            "interpolate",
            ["exponential", 2],
            ["zoom"],
            10,
            ["+", ["*", ["get", "weight"], ["^", 2, -6]], 2],
            24,
            ["+", ["*", ["get", "weight"], ["^", 2, 8]], 2],
          ],
        },
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
      },
      {
        id: "paths_inner",
        type: "line",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "paths",
        filter: [">=", ["get", "weight"], 2],
        minzoom: 0,
        maxzoom: 22,
        paint: {
          "line-color": "#FFFFFF",
          "line-width": [
            "interpolate",
            ["exponential", 2],
            ["zoom"],
            10,
            ["*", ["get", "weight"], ["^", 2, -6]],
            24,
            ["*", ["get", "weight"], ["^", 2, 8]],
          ],
        },
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
      },
    ];

    const buildingLayers: LayerSpecification[] = [
      {
        id: "buildings",
        type: "fill",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings",
        minzoom: 0,
        maxzoom: 22,
        paint: {
          "fill-color": [
            "match",
            ["get", "area"],
            "east",
            "#4eb562",
            "west",
            "#f66950",
            "100th",
            "#43acdd",
            /* default */ "#888888",
          ],
          "fill-opacity": ["step", ["zoom"], 1, 19, 0.15],
        },
      },
    ];
    const buildingIconlayers: LayerSpecification[] = [
      {
        id: "buildings-icon-shadow",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        minzoom: 15,
        maxzoom: 19,
        paint: {
          "circle-radius": 20,
          "circle-blur": 0.7,
          "circle-color": "#000000AA",
          "circle-translate": [0, 2],
        },
      },
      {
        id: "buildings-icon-background",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        minzoom: 15,
        maxzoom: 19,
        paint: {
          "circle-radius": 16,
          "circle-color": "#00AAFF",
          "circle-stroke-color": "#FFFFFF",
          "circle-stroke-width": 2,
        },
      },
      {
        id: "buildings-label",
        type: "symbol",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        minzoom: 15,
        maxzoom: 19,
        layout: {
          "icon-image": MAP_ICONS["material-symbols:source-environment"],
          "icon-padding": 0,
          "text-padding": 0,
          "text-field": ["get", "name"],
          "text-size": 16,
          "text-max-width": 16,
          "text-offset": [0, 1.5],
        },
        paint: {
          "text-color": "#000000",
          "icon-color": "#FFFFFF",
          "text-halo-color": "#FFFFFF",
          "text-halo-width": 2,
        },
      },
      {
        id: "buildings-alt-label",
        type: "symbol",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "buildings_label",
        minzoom: 17,
        maxzoom: 19,
        layout: {
          "text-padding": 0,
          "text-allow-overlap": true,
          "text-ignore-placement": true,
          "text-field": ["get", "altname"],
          "text-size": 12,
          "text-anchor": "top",
          "text-offset": [0, 3],
        },
        paint: {
          "text-color": "#000000",
          "text-halo-color": "#FFFFFF",
          "text-halo-width": 3,
        },
      },
    ];

    const floorIconFilter: FilterSpecification = [
      "all",
      ["==", ["get", "floor"], floor.value],
      ["!", ["in", ["get", "type"], ["literal", ["corridor", "misc"]]]],
    ];

    const extrusionLayers: LayerSpecification[] = [
      {
        id: "building-extrusion",
        type: "fill-extrusion",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors",
        minzoom: 0,
        maxzoom: 22,
        layout: {
          visibility: shouldUseExtrusion.value ? "visible" : "none",
        },
        filter: [
          "any",
          ["<", ["zoom"], 19],
          ["<=", ["get", "floor"], floor.value],
        ],
        paint: {
          "fill-extrusion-color": [
            "match",
            ["get", "area"],
            "east",
            "#4eb562",
            "west",
            "#f66950",
            "100th",
            "#43acdd",
            /* default */ "#888888",
          ],
          "fill-extrusion-base": ["*", ["-", ["get", "floor"], 1], 5],
          "fill-extrusion-opacity": 1,
          "fill-extrusion-vertical-gradient": false,
          "fill-extrusion-height": ["*", ["get", "floor"], 5],
        },
      },
    ];

    const floorLayers: LayerSpecification[] = [
      {
        id: "floors",
        type: "fill",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors",
        minzoom: 19,
        maxzoom: 22,
        filter: ["==", ["get", "floor"], floor.value],
        layout: {
          visibility: shouldUseExtrusion.value ? "none" : "visible",
        },
        paint: {
          "fill-color": [
            "match",
            ["get", "type"],
            "misc",
            "#969696",
            "corridor",
            "#EAEAEA",
            "elevator",
            "#C8C8C8",
            "stairs",
            "#C8C8C8",
            "lecture_room",
            "#D3F1FF",
            "wc_universal",
            "#AC8DCE",
            "wc_unknown",
            "#C7A3C6",
            "wc_men",
            "#8DA2DB",
            "wc_women",
            "#CE8D9B",
            "common_space",
            "#FFEBA6",
            "office",
            "#B1E4B2",
            "#31A6D4",
          ],
          "fill-outline-color": "#232323",
        },
      },
      {
        id: "floors-icon-shadow",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors_label",
        minzoom: 19,
        maxzoom: 22,
        filter: floorIconFilter,
        layout: {
          visibility: shouldUseExtrusion.value ? "none" : "visible",
        },
        paint: {
          "circle-radius": 20,
          "circle-blur": 0.7,
          "circle-color": "#000000AA",
          "circle-translate": [0, 2],
        },
      },
      {
        id: "floors-icon-background",
        type: "circle",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors_label",
        minzoom: 19,
        maxzoom: 22,
        filter: floorIconFilter,
        layout: {
          visibility: shouldUseExtrusion.value ? "none" : "visible",
        },
        paint: {
          "circle-radius": 16,
          "circle-color": [
            "match",
            ["get", "type"],
            "lecture_room",
            "#3abdf9",
            "wc_universal",
            "#8737dc",
            "wc_unknown",
            "#9527b1",
            "wc_men",
            "#234ec7",
            "wc_women",
            "#c72347",
            "common_space",
            "#f7c71c",
            "office",
            "#0ca70e",
            "#969696",
          ],
          "circle-stroke-color": "#FFFFFF",
          "circle-stroke-width": 2,
        },
      },
      {
        id: "floors-label",
        type: "symbol",
        source: UEC_MAP_SOURCE_ID,
        "source-layer": "floors_label",
        minzoom: 19,
        maxzoom: 22,
        filter: floorIconFilter,
        layout: {
          visibility: shouldUseExtrusion.value ? "none" : "visible",
          "icon-image": [
            "match",
            ["get", "type"],
            "elevator",
            MAP_ICONS["material-symbols:elevator-outline"],
            "stairs",
            MAP_ICONS["material-symbols:stairs-2"],
            "lecture_room",
            MAP_ICONS["map:school"],
            "wc_universal",
            MAP_ICONS["map:toilet"],
            "wc_unknown",
            MAP_ICONS["map:toilet"],
            "wc_men",
            MAP_ICONS["map:male"],
            "wc_women",
            MAP_ICONS["map:female"],
            "common_space",
            MAP_ICONS["material-symbols:source-environment"],
            "office",
            MAP_ICONS["material-symbols:checkbook"],
            MAP_ICONS["material-symbols:source-environment"],
          ],
          "icon-padding": 0,
          "text-padding": 0,
          "text-field": ["get", "name"],
          "text-size": 14,
          "text-max-width": 16,
          "text-offset": [0, 1.5],
          "icon-allow-overlap": true,
          "text-allow-overlap": true,
        },
        paint: {
          "text-color": "#000000",
          "icon-color": "#FFFFFF",
          "text-halo-color": "#FFFFFF",
          "text-halo-width": 2,
        },
      },
    ];

    return buildMapStyle({
      version: 8,
      sources: {},
      layers: [
        ...areaLayers,
        ...pathLayers,
        ...buildingLayers,
        ...extrusionLayers,
        ...buildingIconlayers,
        ...floorLayers,
      ],
    });
  });
